calorie_app/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.views.static import serve
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calories.urls')),

    # url(r'^media/(?P<path>.*)$', serve,
    #     {'document_root':       settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,
    #     {'document_root': settings.STATIC_ROOT}),
]

calories/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . views import HomePageView, LoginPage, LogOutPage, select_food, add_food, RegisterPage, ProfilePage, update_food, delete_food, developers, tracker, about, calculator, AnalyticsPageView
from . import views

urlpatterns = [
    path('', HomePageView, name='home'),
    path('login/', LoginPage, name='login'),
    path('logout/', LogOutPage, name='logout'),
    path('select_food/', select_food, name='select_food'),
    path('add_food/', add_food, name='add_food'),
    path('update_food/<str:pk>/', update_food, name='update_food'),
    path('delete_food/<str:pk>/', delete_food, name='delete_food'),
    path('register/', RegisterPage, name='register'),
    path('profile/', ProfilePage, name='profile'),
    path('developers/', developers, name='developers'),
    path('tracker/', tracker, name='tracker'),
    path('about/', about, name='about'),
    path('analytics/', AnalyticsPageView, name='analytics'),
    path('calculator/', calculator, name='calculator'),
    path('allGender/', views.allGender, name='allGender')
]

urlpatterns += staticfiles_urlpatterns()

calories/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import date

# Create your models here. Changes


class Gender(models.Model):
    gender = models.TextField(default=None)
    user = models.TextField(default=None)

    def __str__(self):
        return self.user


class Count(models.Model):
    count = models.TextField(default=None)

    def __str__(self):
        return self.count


class Food(models.Model):
    name = models.CharField(max_length=200, null=False)
    quantity = models.PositiveIntegerField(null=False, default=0)
    calorie = models.FloatField(null=False, default=0)
    nutrition = models.CharField(max_length=200, null=False, default='Carbs')
    person_of = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Profile(models.Model):
    person_of = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    calorie_count = models.FloatField(default=0, null=True, blank=True)
    food_selected = models.ForeignKey(
        Food, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.FloatField(default=0)
    total_calorie = models.FloatField(default=0, null=True)
    date = models.DateField(auto_now_add=True)
    calorie_goal = models.PositiveIntegerField(default=0)
    all_food_selected_today = models.ManyToManyField(
        Food, through='PostFood', related_name='inventory')

    def save(self, *args, **kwargs):  # new
        if self.food_selected != None:
            self.amount = (self.food_selected.calorie /
                           self.food_selected.quantity)
            self.calorie_count = self.amount*self.quantity
            self.total_calorie = self.calorie_count + self.total_calorie
            calories = Profile.objects.filter(person_of=self.person_of).last()
            PostFood.objects.create(profile=calories, food=self.food_selected,
                                    calorie_amount=self.calorie_count, amount=self.quantity)
            self.food_selected = None
            super(Profile, self).save(*args, **kwargs)

        else:
            super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.person_of.username)


class PostFood(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    calorie_amount = models.FloatField(default=0, null=True, blank=True)
    amount = models.FloatField(default=0)

templates/about.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<section class=" mb-20">
    <!-- Changes for 7/21/2022 -->
    <h1 class="text-4xl lg:text-5xl text-green text-center mt-16 mb-12">About CaloRight</h1>

    <div class="contain flex flex-col md:flex-row gap-4 justify-center items-center">
        <img src="{% static 'media/favicon.svg' %}" alt="CaloRight Logo" class=" w-1/2 md:w-full">
        <div class="max-w-3xl">
            <p>CaloRight is a web application used to track a user’s calorie intake every day. To meet the application
                objectives, useful information was added. It includes the daily consumption and the breakdown of the
                total
                nutrient. It tackles what food was taken, how many carbohydrates were consumed, proteins, fats, and the
                most
                important information, the calories consumed. To track the calories, the amount will be calculated using
                the
                basic operations.
            </p>
            <br>
            <p>
                In addition, a TDEE calculator will be included to set a user’s goal. It is a calculator to determine
                the
                number of calories that a person should consume to reach their goals like dieting, gaining weight, or
                being
                healthy. It also contains the know-how and other information about the calorie tracker, health tips, and
                such. With the provided features, users will be fit and healthy in the right way.</p>
        </div>
    </div>

    <div
        class="flex flex-col flex-wrap justify-between items-center md:flex-row gap-4 p-4 my-20 border-t border-b border-white/10">
        <img src="{% static 'media/django.png' %}" alt="CaloRight Logo" class="max-w-xs">
        <img src="{% static 'media/python.png' %}" alt="CaloRight Logo" class="max-w-xs">
        <img src="{% static 'media/tailwind.png' %}" alt="CaloRight Logo" class="max-w-xs">
    </div>
</section>


{% endblock content %}

templates/add_food.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<section>
    <div class="contain flex justify-center align-center flex-col text-center w-full my-12">
        <div class="flex justify-center px-4">
            <img src="{% static 'media/tracker-logo.svg' %}" class="px-4" alt="Tracker Logo" style="max-width: 10rem;">
        </div>
        <h1 class="headline text-[#C8FAC8] text-4xl py-5 font-bold">Adding Food</h1>
        <h2 class="text-3x1 italic hover:underline text-green"><a href="{% url 'profile' %}">Back to Profile</a>
    </div>

    <div class="w-full contain px-8 flex justify-center items-center my-7 mx-auto flex-col lg:flex-row space-y-4">

        <div class="w-full border-green-200 max-w-md border-4 rounded-lg p-8 flex flex-col lg:w-full md:max-w-2x1">

            <div class="py-3 md:flex text-sm flex flex-col ">
                <form method="POST" action="" class="login_form flex flex-col gap-4">
                    {% csrf_token %}
                    <label for="name" class="leading-7 text-[#C8FAC8] text-2xl text-sm">Food
                        Name
                    </label>

                    <input type="text" id="name" name="name" placeholder="Enter Food Name" value="{{field}}"
                        class="w-full bg-transparent rounded border border-gray-300 focus:border-[#C8FAC8] focus:ring-2 focus:ring-[#C8FAC8] text-base outline-none text-white py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    <label for="quantity" class="leading-7 text-[#C8FAC8] text-2xl"> Quantity
                    </label>
                    <input type="number" id="quantity" name="quantity" placeholder="Enter Quantity" value="{{field}}"
                        class="w-full bg-transparent rounded border border-gray-300 focus:border-[#C8FAC8] focus:ring-2 focus:ring-[#C8FAC8] text-base outline-none text-white py-1 px-3 leading-8 transition-colors duration-200 ease-in-out ">
                    <label for="calorie" class="leading-7 text-[#C8FAC8] text-2xl">Calorie
                    </label>
                    <input type="number" id="calorie" name="calorie" placeholder="Enter Calorie" value="{{field}}"
                        class="w-full bg-transparent rounded border border-gray-300 focus:border-[#C8FAC8] focus:ring-2 focus:ring-[#C8FAC8] text-base outline-none text-white py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                    <label for="calorie" class="leading-7 text-[#C8FAC8] text-2xl">Nutrition
                    </label>
                    <input type="text" id="nutrition" name="nutrition" placeholder="Enter nutrition" value="{{field}}"
                        class="w-full bg-transparent rounded border border-gray-300 focus:border-[#C8FAC8] focus:ring-2 focus:ring-[#C8FAC8] text-base outline-none text-white py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">

                    <button type="submit" value="select"
                        class="w-full bg-green-300 text-black  py-3 rounded-lg font-bold text-2xl">Add
                    </button>

                </form>
            </div>
        </div>

        <form method="get">
            <div class="px-8 max-width text-center flex flex-col gap-2 lg:text-left ">
                <div class="border-[#C8FAC8] border-4 rounded-lg px-8 space-y-2 px-8">
                    <h1 class="leading-7 text-black text-2xl py-4">
                        {{ myFilter.form }} </h1>

                    <div class="flex justify-center py-0">
                        <button
                            class="bg-green-300 my-5 text-black p-3 px-6 rounded-lg font-bold text-2xl">Search</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="contain w-full flex-col">
        <h1 class="headline text-[#C8FAC8] text-3xl py-5 md:text-2xl lg:text-5xl font-bold text-center"> All Food Items
        </h1>
        <table class="table-auto border-collapse border border-green-300 mt-5 w-full">
            <thead class="bg-green text-black lg:text-3xl">
                <tr>
                    <th class="border border-green-300">Food Name</th>
                    <th class="border border-green-300">Calories</th>
                    <th class="border border-green-300">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for food in food_items %}
                <tr class="text-center py-3">
                    <td class="border border-green-300 py-1">{{ food.name }}</td>
                    <td class="border border-green-300 py-1">{{ food.calorie }}</td>
                    <td class="border border-green-300 py-1">{{ food.quantity }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</section>

{% endblock content %}

templates/analytics.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<section class="contain mb-20">
    <h1 class="text-4xl lg:text-5xl text-green text-center mt-16 mb-12">Analytics</h1>

    <div class="contain flex flex-col md:flex-row justify-between items-center gap-4">
        <canvas id="numberOfUsersChart" data-all="{{ users_count }}" data-new="{{ user_new_count }}"
            data-guess="{{ guess_users }}"></canvas>
        <canvas id="usersGenderPercentage"></canvas>
    </div>

</section>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
<script>
    const existingUsers = jQuery("#numberOfUsersChart").data("all");
    const newUsers = jQuery("#numberOfUsersChart").data("new");
    const guessUsers = jQuery("#numberOfUsersChart").data("guess");
    console.log(existingUsers, newUsers);
    const ctx = document.getElementById('numberOfUsersChart').getContext('2d');
    const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Guest', 'New User', 'Overall Users'],
            datasets: [
                {
                    label: 'Number of Users',
                    data: [guessUsers, newUsers, existingUsers],
                    backgroundColor: [
                        '#508278',
                        '#82FF87',
                        '#C8FAC8',
                    ],
                }
            ]
        },
        options: {

            scales: {
                x: {
                    ticks: {
                        color: 'white',
                    },
                },
                y: {
                    ticks: {
                        color: 'white',
                    },
                    beginAtZero: true
                }
            }
        }
    });

    const ctxGender = document.getElementById('usersGenderPercentage').getContext('2d');
    const myChartGender = new Chart(ctxGender, {
        type: 'doughnut',
        data: {
            labels: ['Female', 'Male', 'Rather Not to Say'],
            datasets: [{
                label: 'Gender Analytics',
                color: 'white',
                data: [{{ genderFemaleCount }}, {{ genderMaleCount }}, {{ genderOtherCount }}],
    backgroundColor: [
        '#508278',
        '#82FF87',
        '#C8FAC8',
    ],
        hoverOffset: 4
            }]
        },
    options: {
        elements: {
            arc: {
                borderWidth: 0
            }
        },
        scales: {
            x: {
                ticks: {
                    color: 'white',
                    },
            },
            y: {
                ticks: {
                    color: 'white',
                    },
                beginAtZero: true
            }
        }
    }
    });


</script>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>


<head>
  <title>CaloRight</title>
  <meta charset="utf-8">
  <meta property="og:title" content=CaloRight>
  <meta property="og:site_name" content=CaloRight>
  <meta property="og:url" content=https://caloright.herokuapp.com />
  <meta property="og:description" content=CaloRight is a web application used to track a user’s calorie intake every
    day. To meet the application objectives, useful information was added. It includes the daily consumption and the
    breakdown of the total nutrient.>
  <meta property="og:type" content=video.other>
  <meta property="og:image" content=https://i.ibb.co/nrjtMjN/og-image.jpg>

  <link rel="apple-touch-icon" sizes="57x57" href="{% static 'media/favicon/apple-icon-57x57.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'media/favicon/site.webmanifest' %}">
  <!-- Changes for 7/21/2022 -->

  <link href="{% static 'css/base.css' %}" rel="stylesheet">

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
  <script src="https://cdn.tailwindcss.com"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"
    integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <style>
    label {
      color: white;
    }

    #id_food_selected,
    #id_quantity,
    #id_username,
    #id_email,
    #id_password1,
    #id_password2,
    #id_food_name,
    #id_calorie_goal {
      display: block;
      padding: 1em;
      background-color: transparent;
      border: 1px solid rgba(255, 255, 255, 0.1);
      color: white;
      width: 100%;
      margin-top: 1em;
    }

    #id_food_selected {
      margin-bottom: 1em;
    }

    .select_btn {
      width: 50%;
      border: 1px solid rgba(255, 255, 255, 0.1);
    }

    @media only screen and (max-width: 767px) {
      .select_btn {
        width: 100%;
      }
    }

    #id_password2 {
      margin-bottom: 1em;
    }

    canvas {
      width: 100% !important;
      max-width: 500px;
      max-height: 350px;
    }
  </style>
</head>

<body>

  <header id="header" class="rounded">
    <nav id="site-menu" class="flex flex-col lg:flex-row w-full justify-between items-center px-4 lg:px-6 py-1 ">
      <div
        class="w-full lg:w-auto self-start lg:self-center flex flex-row lg:flex-none flex-no-wrap justify-between items-center">
        <a href={% url 'home' %} class="no-underline py-1">
          <img src="{% static 'media/logo-caloright.svg' %}" alt="CaloRight Logo">
        </a>
        <button id="menuBtn" class="hamburger block lg:hidden focus:outline-none" type="button" onclick="navToggle();">
          <span class="hamburger__top-bun"></span><span class="hamburger__bottom-bun"></span>
        </button>
      </div>
      <div id="menu"
        class="w-full gap-4 lg:w-auto self-end lg:self-center lg:flex flex-col lg:flex-row items-center h-full py-1 pb-4 lg:py-0 lg:pb-0 hidden">
        <a class="text-dark uppercase" href="/">HOME</a>
        <a class="text-dark uppercase" href="/tracker">TRACKER</a>
        {% if user.is_staff %}
        <a class="text-dark uppercase" href="/analytics">ANALYTICS</a>
        {% endif %}
        <a class="text-dark uppercase" href="/calculator">CALCULATOR</a>
        <a class="text-dark uppercase" href="/about">ABOUT</a>
        <a class="text-dark uppercase" href="/developers">DEVELOPERS</a>
      </div>
    </nav>
  </header>


  <!-- <a href={% url "home" %}>
    <h1 class="logo text-center">Calorie Drive</h1>
  </a> -->

  <!-- <nav id="navbar-primary" class="navbar navbar-expand-lg navbar-default active" role="navigation">

    <div class="container">
      <div class="navbar-header">

        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#resNav"
          id='navbar-toggler'>
          <span class="navbar-toggler-icon" id="ham"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="resNav">
        <ul class="navbar-nav justify-content-center">
          {% with url_name=request.resolver_match.url_name %}
          <li class="nav-item"><a class="nav-link  {% if url_name == 'home' %} active{% endif %}" href={% url "home"
              %}>Home</a></li>
          <li class="nav-item"><a class="nav-link {% if url_name == 'profile' %} active{% endif %}" href={%
              url "profile" %}>Profile</a></li>
          <li class="nav-item"><a class="nav-link {% if url_name == 'add_food' %} active{% endif %}" href={%
              url "add_food" %}>Add Food</a></li>
          <li class="nav-item"><a class="nav-link {% if url_name == 'select_food' %} active{% endif %}" href={%
              url "select_food" %}>Select Food</a></li>
          {% endwith %}
        </ul>
      </div>

    </div>
  </nav> -->

  <!-- header role="banner" -->
  {% block content %}
  {% endblock content %}


  <footer class="contain border-t border-white/10 mb-10">
    <div class="flex flex-col gap-4 mt-12 justify-center items-center">
      <a href={% url 'home' %} class="no-underline py-1">
        <img src="{% static 'media/logo-caloright.svg' %}" alt="CaloRight Logo">
      </a>

      <nav class="flex flex-row flex-wrap justify-center items-center gap-6">
        <a class="px-4 py-2 w-full md:w-1/3  border-b border-white/10 text-dark uppercase" href="/">HOME</a>
        <a class="px-4 py-2 w-full md:w-1/3  border-b border-white/10 text-dark uppercase" href="/tracker">TRACKER</a>
        <a class="px-4 py-2 w-full md:w-1/3  border-b border-white/10 text-dark uppercase"
          href="/analytics">ANALYTICS</a>
        <a class="px-4 py-2 w-full md:w-1/3  border-b border-white/10 text-dark uppercase"
          href="/calculator">CALCULATOR</a>
        <a class="px-4 py-2  w-full md:w-1/3 border-b border-white/10 text-dark uppercase" href="/about">ABOUT</a>
        <a class="px-4 py-2  w-full md:w-1/3  border-b border-white/10 text-dark uppercase"
          href="/developers">DEVELOPERS</a>
        <a class="px-4 py-2  w-full md:w-1/3 border-b border-white/10 text-dark uppercase"
          href="{% url 'logout' %}">Logout</a>
      </nav>

      <p class="text-sm text-white/50 my-5">Copyright © 2022. All rights Reserved.</p>
    </div>
  </footer>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

  <script>

    var nav = document.getElementById('site-menu');
    var header = document.getElementById('top');

    function navToggle() {
      var btn = document.getElementById('menuBtn');
      var nav = document.getElementById('menu');

      btn.classList.toggle('open');
      nav.classList.toggle('flex');
      nav.classList.toggle('hidden');
    }

  </script>

</body>

</html>

templates/delete_food.html
{% extends 'base.html' %}

{% block content %}

<section>
	<div class="contain p-5 my-5">
		<div class="box-content border-2 border-green-300 flex justify-center text-center align-center flex-col p-12 h-full"
			style="max-width: 80vw;">
			<p class="text-center text-3xl">Are you sure you want to delete {{ food }} ?</p>
			<form method="POST" action="{% url 'delete_food' food.id %}" class="text-center text-green">
				{% csrf_token %}
				<a href="{% url 'profile' %}" class="hover:underline">Cancel</a>
				<input type="submit" name="Confirm" class="hover:underline">
			</form>
		</div>
	</div>
</section>




{% endblock content %}

templates/developers.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

<section class="contain mb-20">
    <h1 class="text-4xl lg:text-5xl text-green text-center mt-16 mb-12">Developers</h1>

    <div class="flex flex-col md:flex-row flex-wrap gap-4 justify-center items-center">
        <div class="w-64 flex flex-col gap-2 justify-center items-center border border-white/10 p-4">
            <img src="{% static 'media/luwi.jpeg' %}" alt="CaloRight Logo"
                class="w-40 bg-white rounded-full border border-white/10">
            <h1 class="uppercase font-bold text-center ">Louie Jocson</h1>
        </div>

        <div class="w-64 flex flex-col gap-2 justify-center items-center border border-white/10 p-4">
            <img src="{% static 'media/tin.png' %}" alt="CaloRight Logo"
                class="w-40 rounded-full border border-white/10">
            <h1 class="uppercase font-bold text-center ">Christine Faith Timpug</h1>
        </div>

        <div class="w-64 flex flex-col gap-2 justify-center items-center border border-white/10 p-4">
            <img src="https://tip.instructure.com/files/5112820/download?download_frd=1&verifier=ihOhMXts4yqYF2RahDLQ42WvHTDvNpO9Eq8BHMOh"
                alt="CaloRight Logo" class="w-40 rounded-full border border-white/10">
            <h1 class="uppercase font-bold text-center ">Cassandra Brucelo</h1>
        </div>

        <div class="w-64 flex flex-col gap-2 justify-center items-center border border-white/10 p-4">
            <img src="{% static 'media/redd.png' %}" alt="CaloRight Logo"
                class="w-40 rounded-full border border-white/10">
            <h1 class="uppercase font-bold text-center ">Janus Redd Regal</h1>
        </div>
    </div>
</section>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto my-5 p-3" style="max-width: 35rem;">
    <div class="login">
        <div class="login-screen p-4">
            <div class="app-title my-3">
                <h1 class="text-4xl lg:text-5xl text-center text-green mb-5">User Log In</h1>
            </div>

            <form method="POST" action="" class="login-form my-3">
                {% csrf_token %}
                <div class="control-group my-2">
                    <input type="text" name="username" placeholder="Username..." class="form-control mt-3 block w-full p-3 bg-transparent border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
                    focus:outline-none
                    focus:border-green-300 focus:ring-1 focus:ring-green-500">

                </div>

                <div class="control-group">
                    <input type="password" name="password" placeholder="Password..." class="form-control my-3 block w-full p-3 bg-transparent border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
                    focus:outline-none
                    focus:border-green-300 focus:ring-1 focus:ring-green-500">
                </div>



                <input
                    class="p-2 bg-green-300 rounded text-black uppercase text-sm block w-full mx-auto hover:bg-green-500 font-bold"
                    type="submit" value="Login">



            </form>
            {% for message in messages %}
            <p id="messages" class="italic">{{message}}</p>
            {% endfor %}

            <div class="pt-8">
                <div class="d-flex justify-content-center links pt-5 text-center">
                    Don't have an account? <a href="/register" class="ml-2  hover:underline underline-offset-4">Sign
                        Up</a>
                </div>

            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto my-5 p-3" style="max-width: 35rem;">
  <div class="login">
    <div class="login-screen p-4">
      <div class="app-title my-3">
        <h1 class="text-4xl lg:text-5xl text-center text-green mb-5">User Register</h1>
      </div>

      <form method="POST" action="" class="login-form">
        {% csrf_token %}
        <div class="form-control">
          {{ form.username }}

        </div>

        <div class="control-group">
          {{ form.email}}
        </div>
        <div class="control-group">
          {{ form.password1 }}
        </div>
        <div class="control-group">
          {{ form.password2 }}
        </div>
        <input
          class="p-2 bg-green-300 rounded text-black uppercase text-sm block w-full mx-auto hover:bg-green-500 font-bold"
          type="submit" name="Register">

      </form>
      {{ form.errors }}
      <div class="d-flex justify-content-center links mt-8 text-center">
        Already have an account? <a href="{% url 'login' %}" class="ml-4 hover:underline underline-offset-4">Login</a>
      </div>
    </div>
  </div>
</div>

<script>

  //Query All input fields
  var form_fields = document.getElementsByTagName('input')
  form_fields[1].placeholder = 'Username..';
  form_fields[2].placeholder = 'Email..';
  form_fields[3].placeholder = 'Enter password...';
  form_fields[4].placeholder = 'Re-enter Password...';


  for (var field in form_fields) {
    form_fields[field].className += ' form-control'
  }
</script>

{% endblock content %}